# Written by copier — don't edit by hand. `copier update` reads _commit to know
# which template version this project was last brought up to.
_commit: 3022d3d
_src_path: gh:PeterFriedrich/cc-data-project-template
